### ISSUE TITLE
Missing TEI elements in Gellerts "Die zärtlichen Schwestern" (gdc:n750.0)

### ISSUE THREAD

**Issue by BenjaminKrautter** [quadrama/Corpus#3]
Play: C. F. Gellert: "Die zärtlichen Schwestern": gdc:n750.0

Issue: gdc:n750.0 should have 12 Scene in Act I and 20 Scenes in Act III; `fstat()` shows 11 in Act I and 18 in Act III.

Problem: This is caused by the seventh scene. It's present in the TEI, but it doesn't have a `sp` element and therefore no speaker:

```
        <div>
          <div>
            <desc>
              <title>7. Auftritt</title>
            </desc>
          </div>
          <div type="text">
            <div type="h4">
              <head>Siebenter Auftritt</head>
              <stage>
                <hi>Julchen allein.</hi>
              </stage>
              <p>Wie? Er geht? Aber warum bin ich so unruhig? Ich liebe ihn ja nicht ... Nein, ich bin ihm nur gewogen. Es ist doch ein unerträglicher Stolz, daß er mich verläßt. Aber habe ich ihn etwan beleidiget? Er ist ja sonst so vernünftig und so großmütig ... Nein, nein, er liebt mich nicht. Es muß Verstellung gewesen sein. Ich habe heute ein recht mürrisches Wesen. <hi>Lottchen tritt unvermerkt herein.</hi> Wenn ich nur meine Laute hier hätte, ich wollte ...</p>
            </div>
          </div>
        </div>
```

**Comment by BenjaminKrautter** [comment]
Kein TEI Problem; falsch verstanden

**Comment by nilsreiter** [comment]
Still, we currently don’t include them as utterances, because we’re looking for `sp` elements. Not a TEI problem, but need to fix the importing.

**Comment by pagelj** [comment]
Moved issue to https://github.com/quadrama/DramaNLP/issues/62

**Comment by pagelj** [comment]
The import has been fixed now in https://github.com/quadrama/DramaNLP/commit/38947fe4ba17e31aa76b767106d84001f9030a25 and the scenes will included in  the utterances table.
The speaker field will be empty, since there is no reliable way to infer who is speaking in a general way.
